#! /usr/bin/env python

# --------------------------------------------------------------------
import sys, os, subprocess as sp, resource, datetime as dt

# --------------------------------------------------------------------
def _main():
    if len(sys.argv)-1 == 0:
        print >>sys.stderr, 'Usage: %s [bin] [args...]' % (sys.argv[0])

    rcode = sp.call(sys.argv[1:])

    if rcode == 0:
        rsr = resource.getrusage(resource.RUSAGE_CHILDREN)
        rsr = dt.timedelta(seconds = int(10 * rsr.ru_utime) / 10.)
        print >>sys.stderr, "%s s. [%s]" % (rsr, ' '.join(sys.argv[1:]))

    exit(rcode)

# --------------------------------------------------------------------
if __name__ == '__main__':
    _main()
